[common]
host=90.90.47.123
port=3306
database=collect
user=root
password=shfkd2023^_

[collect]
input_dir=/local/AIRFLOW/template/dags/collect
output_dir=/local/AIRFLOW/template/dags/collect/product
tags=COLLECT
query=SELECT 
    ci.PROTOCOL_CD, 
    ci.INTERFACE_ID, 
    ci.SYSTEM_CD, 
    ci.INTERFACE_CYCLE,
    ci.IP_NET, 
    ci.JOB_SCHEDULE_EXP, 
    sc.SYSTEM_NM, 
    ci.interface_nm as DESCRIPTION,
    ci.dag_args
    FROM collect_interface ci 
    LEFT JOIN system_code sc  
    ON ci.system_cd = sc.system_cd
    WHERE ci.USE_YN = 'Y';

; ci.dag_args
; IFNULL(CAST(ci.dag_args->>'$.max_active_runs' AS UNSIGNED), 8) AS MAX_ACTIVE_RUNS,
; IFNULL(CAST(ci.dag_args->>'$.max_active_tasks' AS UNSIGNED), 24) AS MAX_ACTIVE_TASKS,
; IFNULL(CAST(ci.dag_args->>'$.retries' AS UNSIGNED), 2) AS RETRIES

[provide]
input_dir=/local/AIRFLOW/template/dags/provide
output_dir=/local/AIRFLOW/template/dags/provide/product
tags=PROVIDE
query=SELECT pi.PROTOCOL_CD, pi.INTERFACE_ID, pi.system_cd, pi.INTERFACE_CYCLE, 
    pt.IP_NET, sc.SYSTEM_NM, pi.interface_nm as DESCRIPTION  
    FROM provide_interface pi 
    LEFT JOIN system_code sc on pi.system_cd = sc.system_cd 
    LEFT JOIN provide_target pt on pt.target_id = pi.target_id 
    WHERE pi.USE_YN='Y' and pi.run_by = 'trigger'
